# Site settings
title: Jonty Cawley-Graham
email: jontycg@gmail.com
url: https://jontycg.github.io/
description: "Adaptable junior developer with a Bsc in Computer Science seeking opportunities in Auckland, New Zealand."
keywords: "developer, dev, auckland, jonty, cawley, graham, cawley-graham, web, android, software, junior"
skills: "Adaptable Junior Developer with a BSc in Computer Science Seeking Opportunities"
meta_author: Cawley-Grahan Jonty

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 5F9F9F
  primary-rgb: "95, 159, 159" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Jonty Cawley-Graham
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/jontycg
  - title: linkedin
    url: https://www.linkedin.com/in/jonty-cawley-graham-53832a58/
  - title: github
    url: http://github.com/jontycg

# Postal address (add as many lines as necessary)
address:
  - line: Auckland

# Credits content
credits: 'I whipped this site up using <a href = "https://jekyllrb.com/">Jekyll</a> with the <a href = "https://github.com/jeromelachaud/freelancer-theme">Freelancer<a> theme.'

# Build settings
markdown: kramdown
permalink: pretty
